[package]
name = "figurust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
chrono = "0.4.23"

[dependencies]
env_logger.workspace = true
log.workspace = true

thiserror.workspace = true
